version: "3"

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: rastokopal/fact-checking-fe:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: on-failure
    depends_on:
      - api
    networks:
      - fact-checking-network

  api:
    image: rastokopal/fact-checking-api:latest
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_URI_TEST=${MONGO_URI_TEST}
      - NODE_ENV=${NODE_ENV}
      - APP_NAME=${APP_NAME}
      - APP_PORT=${APP_PORT}
      - API_PREFIX=${API_PREFIX}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_TOKEN_EXPIRES_IN=${AUTH_JWT_TOKEN_EXPIRES_IN}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - fact-checking-network

  extract-service:
    image: rastokopal/fact-checking-extract-service:1.0.0
    ports:
      - 8080:8080
    networks:
      - fact-checking-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PWD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    command: [--auth]
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - fact-checking-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  mongodb_data:
  redis_data:

networks:
    fact-checking-network:
      driver: bridge