version: "3"

services:
  api:
    image: rastokopal/fact-checking-api:1.0.0
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - MONGO_URI=mongodb://mongodb:27017/fact_checking_be
      - MONGO_URI_TEST=mongodb://mongodb:27017/fact_checking_be_test
      - NODE_ENV=production
      - APP_NAME=${APP_NAME}
      - APP_PORT=${APP_PORT}
      - API_PREFIX=${API_PREFIX}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_TOKEN_EXPIRES_IN=${AUTH_JWT_TOKEN_EXPIRES_IN}
    depends_on:
      - mongodb
    networks:
      - nesjs-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nesjs-network

volumes:
  mongodb_data:

networks:
    nesjs-network:
      driver: bridge