version: "3"

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: rastokopal/fact-checking-fe:1.0.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: on-failure
    depends_on:
      - api
    networks:
      - fact-checking-network

  api:
    image: rastokopal/fact-checking-api
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/fact_checking_be
      - MONGO_URI_TEST=mongodb://mongodb:27017/fact_checking_be_test
      - NODE_ENV=production
      - APP_NAME=${APP_NAME}
      - APP_PORT=3000
      - API_PREFIX=${API_PREFIX}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_TOKEN_EXPIRES_IN=${AUTH_JWT_TOKEN_EXPIRES_IN}
    depends_on:
      - mongodb
    networks:
      - fact-checking-network

  extract-service:
    image: rastokopal/fact-checking-extract-service:1.0.0
    ports:
      - 8080:8080
    networks:
      - fact-checking-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fact-checking-network

volumes:
  mongodb_data:

networks:
    fact-checking-network:
      driver: bridge